# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chatwoot_client
from chatwoot_client.apis.custom_attributes_api import CustomAttributesApi  # noqa: E501
from chatwoot_client.rest import ApiException


class TestCustomAttributesApi(unittest.TestCase):
    """CustomAttributesApi unit test stubs"""

    def setUp(self):
        self.api = CustomAttributesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_new_custom_attribute_to_account(self):
        """Test case for add_new_custom_attribute_to_account

        Add a new custom attribute  # noqa: E501
        """
        pass

    def test_delete_custom_attribute_from_account(self):
        """Test case for delete_custom_attribute_from_account

        Remove a custom attribute from account  # noqa: E501
        """
        pass

    def test_get_account_custom_attribute(self):
        """Test case for get_account_custom_attribute

        List all custom attributes in an account  # noqa: E501
        """
        pass

    def test_get_details_of_a_single_custom_attribute(self):
        """Test case for get_details_of_a_single_custom_attribute

        Get a custom attribute details  # noqa: E501
        """
        pass

    def test_update_custom_attribute_in_account(self):
        """Test case for update_custom_attribute_in_account

        Update custom attribute in Account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
