# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chatwoot_client
from chatwoot_client.apis.accounts_api import AccountsApi  # noqa: E501
from chatwoot_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_an_account(self):
        """Test case for create_an_account

        Create an Account  # noqa: E501
        """
        pass

    def test_delete_an_account(self):
        """Test case for delete_an_account

        Delete an Account  # noqa: E501
        """
        pass

    def test_get_details_of_an_account(self):
        """Test case for get_details_of_an_account

        Get an account details  # noqa: E501
        """
        pass

    def test_update_an_account(self):
        """Test case for update_an_account

        Update an account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
