# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chatwoot_client
from chatwoot_client.apis.automation_rule_api import AutomationRuleApi  # noqa: E501
from chatwoot_client.rest import ApiException


class TestAutomationRuleApi(unittest.TestCase):
    """AutomationRuleApi unit test stubs"""

    def setUp(self):
        self.api = AutomationRuleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_new_automation_rule_to_account(self):
        """Test case for add_new_automation_rule_to_account

        Add a new automation rule  # noqa: E501
        """
        pass

    def test_delete_automation_rule_from_account(self):
        """Test case for delete_automation_rule_from_account

        Remove a automation rule from account  # noqa: E501
        """
        pass

    def test_get_account_automation_rule(self):
        """Test case for get_account_automation_rule

        List all automation rules in an account  # noqa: E501
        """
        pass

    def test_get_details_of_a_single_automation_rule(self):
        """Test case for get_details_of_a_single_automation_rule

        Get a automation rule details  # noqa: E501
        """
        pass

    def test_update_automation_rule_in_account(self):
        """Test case for update_automation_rule_in_account

        Update automation rule in Account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
