# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chatwoot_client
from chatwoot_client.models.conversation_labels import ConversationLabels  # noqa: E501
from chatwoot_client.rest import ApiException


class TestConversationLabels(unittest.TestCase):
    """ConversationLabels unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConversationLabels(self):
        """Test ConversationLabels"""
        # FIXME: construct object with mandatory attributes with example values
        # model = chatwoot_client.models.conversation_labels.ConversationLabels()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
