# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chatwoot_client
from chatwoot_client.apis.integrations_api import IntegrationsApi  # noqa: E501
from chatwoot_client.rest import ApiException


class TestIntegrationsApi(unittest.TestCase):
    """IntegrationsApi unit test stubs"""

    def setUp(self):
        self.api = IntegrationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_an_integration_hook(self):
        """Test case for create_an_integration_hook

        Create an integration hook  # noqa: E501
        """
        pass

    def test_delete_an_integration_hook(self):
        """Test case for delete_an_integration_hook

        Delete an Integration Hook  # noqa: E501
        """
        pass

    def test_get_details_of_all_integrations(self):
        """Test case for get_details_of_all_integrations

        List all the Integrations  # noqa: E501
        """
        pass

    def test_update_an_integrations_hook(self):
        """Test case for update_an_integrations_hook

        Update an Integration Hook  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
