# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chatwoot_client
from chatwoot_client.models.all_ofconversation_list_data_payload_items import AllOfconversationListDataPayloadItems  # noqa: E501
from chatwoot_client.rest import ApiException


class TestAllOfconversationListDataPayloadItems(unittest.TestCase):
    """AllOfconversationListDataPayloadItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfconversationListDataPayloadItems(self):
        """Test AllOfconversationListDataPayloadItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = chatwoot_client.models.all_ofconversation_list_data_payload_items.AllOfconversationListDataPayloadItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
