# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chatwoot_client
from chatwoot_client.apis.conversations_api_api import ConversationsAPIApi  # noqa: E501
from chatwoot_client.rest import ApiException


class TestConversationsAPIApi(unittest.TestCase):
    """ConversationsAPIApi unit test stubs"""

    def setUp(self):
        self.api = ConversationsAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_a_conversation(self):
        """Test case for create_a_conversation

        Create a conversation  # noqa: E501
        """
        pass

    def test_list_all_contact_conversations(self):
        """Test case for list_all_contact_conversations

        List all conversations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
