# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chatwoot_client
from chatwoot_client.apis.canned_responses_api import CannedResponsesApi  # noqa: E501
from chatwoot_client.rest import ApiException


class TestCannedResponsesApi(unittest.TestCase):
    """CannedResponsesApi unit test stubs"""

    def setUp(self):
        self.api = CannedResponsesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_new_canned_response_to_account(self):
        """Test case for add_new_canned_response_to_account

        Add a New Canned Response  # noqa: E501
        """
        pass

    def test_delete_canned_response_from_account(self):
        """Test case for delete_canned_response_from_account

        Remove a Canned Response from Account  # noqa: E501
        """
        pass

    def test_get_account_canned_response(self):
        """Test case for get_account_canned_response

        List all Canned Responses in an Account  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
