# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chatwoot_client
from chatwoot_client.apis.reports_api import ReportsApi  # noqa: E501
from chatwoot_client.rest import ApiException


class TestReportsApi(unittest.TestCase):
    """ReportsApi unit test stubs"""

    def setUp(self):
        self.api = ReportsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account_conversation_metrics(self):
        """Test case for get_account_conversation_metrics

        Account Conversation Metrics  # noqa: E501
        """
        pass

    def test_get_agent_conversation_metrics(self):
        """Test case for get_agent_conversation_metrics

        Agent Conversation Metrics  # noqa: E501
        """
        pass

    def test_list_all_conversation_statistics(self):
        """Test case for list_all_conversation_statistics

        Get Account reports  # noqa: E501
        """
        pass

    def test_list_all_conversation_statistics_summary(self):
        """Test case for list_all_conversation_statistics_summary

        Get Account reports summary  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
