# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import chatwoot_client
from chatwoot_client.apis.contacts_api_api import ContactsAPIApi  # noqa: E501
from chatwoot_client.rest import ApiException


class TestContactsAPIApi(unittest.TestCase):
    """ContactsAPIApi unit test stubs"""

    def setUp(self):
        self.api = ContactsAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_a_contact(self):
        """Test case for create_a_contact

        Create a contact  # noqa: E501
        """
        pass

    def test_get_details_of_a_contact(self):
        """Test case for get_details_of_a_contact

        Get a contact  # noqa: E501
        """
        pass

    def test_update_a_contact(self):
        """Test case for update_a_contact

        Update a contact  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
