# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apiv1accountsaccountIdconversationsMessageTemplateParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'category': 'str',
        'language': 'str',
        'processed_params': 'object'
    }

    attribute_map = {
        'name': 'name',
        'category': 'category',
        'language': 'language',
        'processed_params': 'processed_params'
    }

    def __init__(self, name=None, category=None, language=None, processed_params=None):  # noqa: E501
        """Apiv1accountsaccountIdconversationsMessageTemplateParams - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._category = None
        self._language = None
        self._processed_params = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if category is not None:
            self.category = category
        if language is not None:
            self.language = language
        if processed_params is not None:
            self.processed_params = processed_params

    @property
    def name(self):
        """Gets the name of this Apiv1accountsaccountIdconversationsMessageTemplateParams.  # noqa: E501

        Name of the template  # noqa: E501

        :return: The name of this Apiv1accountsaccountIdconversationsMessageTemplateParams.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Apiv1accountsaccountIdconversationsMessageTemplateParams.

        Name of the template  # noqa: E501

        :param name: The name of this Apiv1accountsaccountIdconversationsMessageTemplateParams.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def category(self):
        """Gets the category of this Apiv1accountsaccountIdconversationsMessageTemplateParams.  # noqa: E501

        Category of the template  # noqa: E501

        :return: The category of this Apiv1accountsaccountIdconversationsMessageTemplateParams.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this Apiv1accountsaccountIdconversationsMessageTemplateParams.

        Category of the template  # noqa: E501

        :param category: The category of this Apiv1accountsaccountIdconversationsMessageTemplateParams.  # noqa: E501
        :type: str
        """

        self._category = category

    @property
    def language(self):
        """Gets the language of this Apiv1accountsaccountIdconversationsMessageTemplateParams.  # noqa: E501

        Language of the template  # noqa: E501

        :return: The language of this Apiv1accountsaccountIdconversationsMessageTemplateParams.  # noqa: E501
        :rtype: str
        """
        return self._language

    @language.setter
    def language(self, language):
        """Sets the language of this Apiv1accountsaccountIdconversationsMessageTemplateParams.

        Language of the template  # noqa: E501

        :param language: The language of this Apiv1accountsaccountIdconversationsMessageTemplateParams.  # noqa: E501
        :type: str
        """

        self._language = language

    @property
    def processed_params(self):
        """Gets the processed_params of this Apiv1accountsaccountIdconversationsMessageTemplateParams.  # noqa: E501

        The processed param values for template variables in template  # noqa: E501

        :return: The processed_params of this Apiv1accountsaccountIdconversationsMessageTemplateParams.  # noqa: E501
        :rtype: object
        """
        return self._processed_params

    @processed_params.setter
    def processed_params(self, processed_params):
        """Sets the processed_params of this Apiv1accountsaccountIdconversationsMessageTemplateParams.

        The processed param values for template variables in template  # noqa: E501

        :param processed_params: The processed_params of this Apiv1accountsaccountIdconversationsMessageTemplateParams.  # noqa: E501
        :type: object
        """

        self._processed_params = processed_params

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apiv1accountsaccountIdconversationsMessageTemplateParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apiv1accountsaccountIdconversationsMessageTemplateParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
