# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Apiv1accountsaccountIdconversationsMessage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content': 'str',
        'template_params': 'Apiv1accountsaccountIdconversationsMessageTemplateParams'
    }

    attribute_map = {
        'content': 'content',
        'template_params': 'template_params'
    }

    def __init__(self, content=None, template_params=None):  # noqa: E501
        """Apiv1accountsaccountIdconversationsMessage - a model defined in Swagger"""  # noqa: E501
        self._content = None
        self._template_params = None
        self.discriminator = None
        self.content = content
        if template_params is not None:
            self.template_params = template_params

    @property
    def content(self):
        """Gets the content of this Apiv1accountsaccountIdconversationsMessage.  # noqa: E501

        The content of the message  # noqa: E501

        :return: The content of this Apiv1accountsaccountIdconversationsMessage.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this Apiv1accountsaccountIdconversationsMessage.

        The content of the message  # noqa: E501

        :param content: The content of this Apiv1accountsaccountIdconversationsMessage.  # noqa: E501
        :type: str
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content

    @property
    def template_params(self):
        """Gets the template_params of this Apiv1accountsaccountIdconversationsMessage.  # noqa: E501


        :return: The template_params of this Apiv1accountsaccountIdconversationsMessage.  # noqa: E501
        :rtype: Apiv1accountsaccountIdconversationsMessageTemplateParams
        """
        return self._template_params

    @template_params.setter
    def template_params(self, template_params):
        """Sets the template_params of this Apiv1accountsaccountIdconversationsMessage.


        :param template_params: The template_params of this Apiv1accountsaccountIdconversationsMessage.  # noqa: E501
        :type: Apiv1accountsaccountIdconversationsMessageTemplateParams
        """

        self._template_params = template_params

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Apiv1accountsaccountIdconversationsMessage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Apiv1accountsaccountIdconversationsMessage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
