# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CannedResponseCreateUpdatePayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content': 'str',
        'short_code': 'str'
    }

    attribute_map = {
        'content': 'content',
        'short_code': 'short_code'
    }

    def __init__(self, content=None, short_code=None):  # noqa: E501
        """CannedResponseCreateUpdatePayload - a model defined in Swagger"""  # noqa: E501
        self._content = None
        self._short_code = None
        self.discriminator = None
        if content is not None:
            self.content = content
        if short_code is not None:
            self.short_code = short_code

    @property
    def content(self):
        """Gets the content of this CannedResponseCreateUpdatePayload.  # noqa: E501

        Message content for canned response  # noqa: E501

        :return: The content of this CannedResponseCreateUpdatePayload.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this CannedResponseCreateUpdatePayload.

        Message content for canned response  # noqa: E501

        :param content: The content of this CannedResponseCreateUpdatePayload.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def short_code(self):
        """Gets the short_code of this CannedResponseCreateUpdatePayload.  # noqa: E501

        Short Code for quick access of the canned response  # noqa: E501

        :return: The short_code of this CannedResponseCreateUpdatePayload.  # noqa: E501
        :rtype: str
        """
        return self._short_code

    @short_code.setter
    def short_code(self, short_code):
        """Sets the short_code of this CannedResponseCreateUpdatePayload.

        Short Code for quick access of the canned response  # noqa: E501

        :param short_code: The short_code of this CannedResponseCreateUpdatePayload.  # noqa: E501
        :type: str
        """

        self._short_code = short_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CannedResponseCreateUpdatePayload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CannedResponseCreateUpdatePayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
