# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse200(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_id': 'int',
        'user_id': 'int',
        'role': 'str'
    }

    attribute_map = {
        'account_id': 'account_id',
        'user_id': 'user_id',
        'role': 'role'
    }

    def __init__(self, account_id=None, user_id=None, role=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger"""  # noqa: E501
        self._account_id = None
        self._user_id = None
        self._role = None
        self.discriminator = None
        if account_id is not None:
            self.account_id = account_id
        if user_id is not None:
            self.user_id = user_id
        if role is not None:
            self.role = role

    @property
    def account_id(self):
        """Gets the account_id of this InlineResponse200.  # noqa: E501

        The ID of the user  # noqa: E501

        :return: The account_id of this InlineResponse200.  # noqa: E501
        :rtype: int
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this InlineResponse200.

        The ID of the user  # noqa: E501

        :param account_id: The account_id of this InlineResponse200.  # noqa: E501
        :type: int
        """

        self._account_id = account_id

    @property
    def user_id(self):
        """Gets the user_id of this InlineResponse200.  # noqa: E501

        The ID of the user  # noqa: E501

        :return: The user_id of this InlineResponse200.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this InlineResponse200.

        The ID of the user  # noqa: E501

        :param user_id: The user_id of this InlineResponse200.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def role(self):
        """Gets the role of this InlineResponse200.  # noqa: E501

        whether user is an administrator or agent  # noqa: E501

        :return: The role of this InlineResponse200.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this InlineResponse200.

        whether user is an administrator or agent  # noqa: E501

        :param role: The role of this InlineResponse200.  # noqa: E501
        :type: str
        """

        self._role = role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse200, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse200):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
