# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2004(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'account_id': 'int',
        'inbox_id': 'int'
    }

    attribute_map = {
        'id': 'id',
        'account_id': 'account_id',
        'inbox_id': 'inbox_id'
    }

    def __init__(self, id=None, account_id=None, inbox_id=None):  # noqa: E501
        """InlineResponse2004 - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._account_id = None
        self._inbox_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if account_id is not None:
            self.account_id = account_id
        if inbox_id is not None:
            self.inbox_id = inbox_id

    @property
    def id(self):
        """Gets the id of this InlineResponse2004.  # noqa: E501

        ID of the conversation  # noqa: E501

        :return: The id of this InlineResponse2004.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse2004.

        ID of the conversation  # noqa: E501

        :param id: The id of this InlineResponse2004.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def account_id(self):
        """Gets the account_id of this InlineResponse2004.  # noqa: E501

        Account Id  # noqa: E501

        :return: The account_id of this InlineResponse2004.  # noqa: E501
        :rtype: int
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this InlineResponse2004.

        Account Id  # noqa: E501

        :param account_id: The account_id of this InlineResponse2004.  # noqa: E501
        :type: int
        """

        self._account_id = account_id

    @property
    def inbox_id(self):
        """Gets the inbox_id of this InlineResponse2004.  # noqa: E501

        ID of the inbox  # noqa: E501

        :return: The inbox_id of this InlineResponse2004.  # noqa: E501
        :rtype: int
        """
        return self._inbox_id

    @inbox_id.setter
    def inbox_id(self, inbox_id):
        """Sets the inbox_id of this InlineResponse2004.

        ID of the inbox  # noqa: E501

        :param inbox_id: The inbox_id of this InlineResponse2004.  # noqa: E501
        :type: int
        """

        self._inbox_id = inbox_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2004, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2004):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
