# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PortalCreateUpdatePayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'archived': 'bool',
        'color': 'str',
        'config': 'object',
        'custom_domain': 'str',
        'header_text': 'str',
        'homepage_link': 'str',
        'name': 'str',
        'slug': 'str',
        'page_title': 'str',
        'account_id': 'int'
    }

    attribute_map = {
        'archived': 'archived',
        'color': 'color',
        'config': 'config',
        'custom_domain': 'custom_domain',
        'header_text': 'header_text',
        'homepage_link': 'homepage_link',
        'name': 'name',
        'slug': 'slug',
        'page_title': 'page_title',
        'account_id': 'account_id'
    }

    def __init__(self, archived=None, color=None, config=None, custom_domain=None, header_text=None, homepage_link=None, name=None, slug=None, page_title=None, account_id=None):  # noqa: E501
        """PortalCreateUpdatePayload - a model defined in Swagger"""  # noqa: E501
        self._archived = None
        self._color = None
        self._config = None
        self._custom_domain = None
        self._header_text = None
        self._homepage_link = None
        self._name = None
        self._slug = None
        self._page_title = None
        self._account_id = None
        self.discriminator = None
        if archived is not None:
            self.archived = archived
        if color is not None:
            self.color = color
        if config is not None:
            self.config = config
        if custom_domain is not None:
            self.custom_domain = custom_domain
        if header_text is not None:
            self.header_text = header_text
        if homepage_link is not None:
            self.homepage_link = homepage_link
        if name is not None:
            self.name = name
        if slug is not None:
            self.slug = slug
        if page_title is not None:
            self.page_title = page_title
        if account_id is not None:
            self.account_id = account_id

    @property
    def archived(self):
        """Gets the archived of this PortalCreateUpdatePayload.  # noqa: E501

        Status to check if portal is live  # noqa: E501

        :return: The archived of this PortalCreateUpdatePayload.  # noqa: E501
        :rtype: bool
        """
        return self._archived

    @archived.setter
    def archived(self, archived):
        """Sets the archived of this PortalCreateUpdatePayload.

        Status to check if portal is live  # noqa: E501

        :param archived: The archived of this PortalCreateUpdatePayload.  # noqa: E501
        :type: bool
        """

        self._archived = archived

    @property
    def color(self):
        """Gets the color of this PortalCreateUpdatePayload.  # noqa: E501

        Header color for help-center  # noqa: E501

        :return: The color of this PortalCreateUpdatePayload.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this PortalCreateUpdatePayload.

        Header color for help-center  # noqa: E501

        :param color: The color of this PortalCreateUpdatePayload.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def config(self):
        """Gets the config of this PortalCreateUpdatePayload.  # noqa: E501

        Configuration about supporting locales  # noqa: E501

        :return: The config of this PortalCreateUpdatePayload.  # noqa: E501
        :rtype: object
        """
        return self._config

    @config.setter
    def config(self, config):
        """Sets the config of this PortalCreateUpdatePayload.

        Configuration about supporting locales  # noqa: E501

        :param config: The config of this PortalCreateUpdatePayload.  # noqa: E501
        :type: object
        """

        self._config = config

    @property
    def custom_domain(self):
        """Gets the custom_domain of this PortalCreateUpdatePayload.  # noqa: E501

        Custom domain to  display help center.  # noqa: E501

        :return: The custom_domain of this PortalCreateUpdatePayload.  # noqa: E501
        :rtype: str
        """
        return self._custom_domain

    @custom_domain.setter
    def custom_domain(self, custom_domain):
        """Sets the custom_domain of this PortalCreateUpdatePayload.

        Custom domain to  display help center.  # noqa: E501

        :param custom_domain: The custom_domain of this PortalCreateUpdatePayload.  # noqa: E501
        :type: str
        """

        self._custom_domain = custom_domain

    @property
    def header_text(self):
        """Gets the header_text of this PortalCreateUpdatePayload.  # noqa: E501

        Help center header  # noqa: E501

        :return: The header_text of this PortalCreateUpdatePayload.  # noqa: E501
        :rtype: str
        """
        return self._header_text

    @header_text.setter
    def header_text(self, header_text):
        """Sets the header_text of this PortalCreateUpdatePayload.

        Help center header  # noqa: E501

        :param header_text: The header_text of this PortalCreateUpdatePayload.  # noqa: E501
        :type: str
        """

        self._header_text = header_text

    @property
    def homepage_link(self):
        """Gets the homepage_link of this PortalCreateUpdatePayload.  # noqa: E501

        link to main dashboard  # noqa: E501

        :return: The homepage_link of this PortalCreateUpdatePayload.  # noqa: E501
        :rtype: str
        """
        return self._homepage_link

    @homepage_link.setter
    def homepage_link(self, homepage_link):
        """Sets the homepage_link of this PortalCreateUpdatePayload.

        link to main dashboard  # noqa: E501

        :param homepage_link: The homepage_link of this PortalCreateUpdatePayload.  # noqa: E501
        :type: str
        """

        self._homepage_link = homepage_link

    @property
    def name(self):
        """Gets the name of this PortalCreateUpdatePayload.  # noqa: E501

        Name for the portal  # noqa: E501

        :return: The name of this PortalCreateUpdatePayload.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PortalCreateUpdatePayload.

        Name for the portal  # noqa: E501

        :param name: The name of this PortalCreateUpdatePayload.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def slug(self):
        """Gets the slug of this PortalCreateUpdatePayload.  # noqa: E501

        Slug for the portal to display in link  # noqa: E501

        :return: The slug of this PortalCreateUpdatePayload.  # noqa: E501
        :rtype: str
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this PortalCreateUpdatePayload.

        Slug for the portal to display in link  # noqa: E501

        :param slug: The slug of this PortalCreateUpdatePayload.  # noqa: E501
        :type: str
        """

        self._slug = slug

    @property
    def page_title(self):
        """Gets the page_title of this PortalCreateUpdatePayload.  # noqa: E501

        Page title for the portal  # noqa: E501

        :return: The page_title of this PortalCreateUpdatePayload.  # noqa: E501
        :rtype: str
        """
        return self._page_title

    @page_title.setter
    def page_title(self, page_title):
        """Sets the page_title of this PortalCreateUpdatePayload.

        Page title for the portal  # noqa: E501

        :param page_title: The page_title of this PortalCreateUpdatePayload.  # noqa: E501
        :type: str
        """

        self._page_title = page_title

    @property
    def account_id(self):
        """Gets the account_id of this PortalCreateUpdatePayload.  # noqa: E501


        :return: The account_id of this PortalCreateUpdatePayload.  # noqa: E501
        :rtype: int
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this PortalCreateUpdatePayload.


        :param account_id: The account_id of this PortalCreateUpdatePayload.  # noqa: E501
        :type: int
        """

        self._account_id = account_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PortalCreateUpdatePayload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PortalCreateUpdatePayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
