# coding: utf-8

"""
    Chatwoot

    This is the API documentation for Chatwoot server.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: hello@chatwoot.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TeamCreateUpdatePayload(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'allow_auto_assign': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'allow_auto_assign': 'allow_auto_assign'
    }

    def __init__(self, name=None, description=None, allow_auto_assign=None):  # noqa: E501
        """TeamCreateUpdatePayload - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._description = None
        self._allow_auto_assign = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if description is not None:
            self.description = description
        if allow_auto_assign is not None:
            self.allow_auto_assign = allow_auto_assign

    @property
    def name(self):
        """Gets the name of this TeamCreateUpdatePayload.  # noqa: E501

        The name of the team  # noqa: E501

        :return: The name of this TeamCreateUpdatePayload.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TeamCreateUpdatePayload.

        The name of the team  # noqa: E501

        :param name: The name of this TeamCreateUpdatePayload.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """Gets the description of this TeamCreateUpdatePayload.  # noqa: E501

        The description of the team  # noqa: E501

        :return: The description of this TeamCreateUpdatePayload.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this TeamCreateUpdatePayload.

        The description of the team  # noqa: E501

        :param description: The description of this TeamCreateUpdatePayload.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def allow_auto_assign(self):
        """Gets the allow_auto_assign of this TeamCreateUpdatePayload.  # noqa: E501

        If this setting is turned on, the system would automatically assign the conversation to an agent in the team while assigning the conversation to a team  # noqa: E501

        :return: The allow_auto_assign of this TeamCreateUpdatePayload.  # noqa: E501
        :rtype: bool
        """
        return self._allow_auto_assign

    @allow_auto_assign.setter
    def allow_auto_assign(self, allow_auto_assign):
        """Sets the allow_auto_assign of this TeamCreateUpdatePayload.

        If this setting is turned on, the system would automatically assign the conversation to an agent in the team while assigning the conversation to a team  # noqa: E501

        :param allow_auto_assign: The allow_auto_assign of this TeamCreateUpdatePayload.  # noqa: E501
        :type: bool
        """

        self._allow_auto_assign = allow_auto_assign

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TeamCreateUpdatePayload, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TeamCreateUpdatePayload):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
